{{- if .Values.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: {{ .Values.certManager.namespace }}
  labels:
    app: {{ include "cert-manager-webhook.name" . }}
    chart: {{ include "cert-manager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
